magasin.web/Models/Formulaire.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace magasin.web.Models
{
    public class Formulaire
    {
        [Required]
        [StringLength(25)]
        public string Login { get; set; }

        [Required]
        [StringLength(25, ErrorMessage = "Trop long")]
        public string Password { get; set; }

        [Required]
        [StringLength(25)]
        public string Nom { get; set; }

        [Required]
        [StringLength(25, ErrorMessage = "Trop long")]
        public string Prenom { get; set; }

        
        [Required]
        [EmailAddress]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Must be a valid Email Address")]
        public string Email { get; set; }

        
    }
}

magasin.web/Models/ObjectCategorie.cs
using magasin.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace magasin.web.Models
{
    public class ObjectCategorie
    {
        public DAL.Object Obj {get;set;}
        public List<Categorie> Cats { get; set; }

        public ObjectCategorie()
        {
            Obj = new DAL.Object();
        }
        public ObjectCategorie(DAL.Object obj, List<Categorie> cats)
        {
            Obj = obj;
            Cats = cats;
        }
       
    }
}

magasin.web/Controllers/HomeController.cs
using magasin.DAL;
using magasin.web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace magasin.web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            Profil pro = SessionUtils.UserConnected;
            return View(pro);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {


            //if (SessionUtils.UserConnected != null)
            //{

            //    return RedirectToAction("Index");
            //}
            return View();
        }

        [HttpPost]
        public ActionResult Register(Profil pro)
        {

            DAOProfil daoProfil = new DAOProfil();

            Profil prop = daoProfil.create(pro);
            return RedirectToAction("Index");
        }


    }

}

magasin.web/Controllers/ObjectController.cs
using magasin.DAL;
using magasin.web.Infrastructure;
using magasin.web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace magasin.web.Controllers
{
    public class ObjectController : Controller
    {
        private DAOObjet daoObjet = new DAOObjet();
        private DAOCategorie daoCat = new DAOCategorie();

        [HttpGet]
        public ActionResult CreerObjetPHOTO()
        {

            ObjectCategorie oc = new ObjectCategorie();
            oc.Cats = daoCat.readAll();

            return View(oc);
        }

        [HttpPost]
        public ActionResult CreerObjetPHOTO(ObjectCategorie Objectcat, HttpPostedFileBase file)
        {

            var allowedExtensions = new[] {
                    ".Jpg", ".png", ".jpg", ".jpeg"
                        };

            Objectcat.Obj.Photo = file.ToString(); //acceder a l'url  complet

            var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
            var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
            if (allowedExtensions.Contains(ext)) //permet de verifier l'extension de notre fichier   
            {
                string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                                                                          /*string myfile = name + "_" + ext;*/ //appending the name with id  
                string myfile = name + ext;
                // store the file inside ~/project folder(Img)  
                var path = Path.Combine(Server.MapPath("~/images"), file.FileName);
                Objectcat.Obj.Photo = "images/" + myfile;



                file.SaveAs(path);

                //img = DAOObjet.UploadImage(img);
            }
            else
            {
                ViewBag.message = "Please choose only Image file";
            }

            DAL.Object objectEncode = daoObjet.create(Objectcat.Obj);
            //return View();
            return RedirectToAction("AfficherObjet");

        }






        [HttpGet]
        public ActionResult AfficherObjet()
        {

            List<DAL.Object> listObj = new List<DAL.Object>();
            listObj = daoObjet.readAll();

            return View(listObj);
        }

        [HttpGet]
        public ActionResult SaveImageFolder()
        {
            return View();
        }

        public ActionResult DeleteObjet(int id)
        {
            daoObjet.delete(id);
            return RedirectToAction("AfficherObjet");
        }

        [HttpGet]
        public ActionResult AfficherUnObjet(int id)
        {
            DAL.Object ob = daoObjet.read(id);

            return View(ob);
        }

        [HttpGet]
        public ActionResult EditObjet(int id)
        {
            DAL.Object obj = daoObjet.read(id);

            return View(obj);
        }


        [HttpPost]
        public ActionResult EditObjet(DAL.Object obj)
        {
            obj = daoObjet.update(obj);
            if (obj == null) {
                ViewBag.Message = "not possible !";
                return View(obj.IdObjet);

            }

            return RedirectToAction("AfficherObjet", new { id = obj.IdObjet });
        }

        public JsonResult traitementAjax(int valeurId)
        {
            DAL.Object ob = daoObjet.read(valeurId);
            SessionUtils.Panier.Add(ob);
            return Json(SessionUtils.Panier, JsonRequestBehavior.AllowGet); //c'est la façon dont il faut que cela réponde on spécifie le comportement de Json

        }

        public ActionResult afficherPannier()
        {

            return View(SessionUtils.Panier); //revoyer juste une vue du panier
        }
    }

}  





    

magasin.web/Controllers/UserController.cs
using magasin.DAL;
using magasin.web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace magasin.web.Controllers
{
    public class UserController : Controller
    {
        private DAOUser daoUser = new DAOUser();


        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Connection()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Connection(string login, string password)
        {
            Session["admin"] = "";
            Profil profilTrouve = daoUser.Connection(login, password);
            if (profilTrouve != null)
            {
                SessionUtils.UserConnected = profilTrouve;
                // quand le pro est null ca veut dire que le login ne marche pas
                // alors il faut pas controler le profile mais arrêter l'application & mettre erreur sur le page
                Session["profil"] = profilTrouve.Prenom + " " + profilTrouve.Nom.Substring(0, 1);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("About", "Home");
            }


        }

        public ActionResult Deconnexion()
        {
            Session["userConnected"] = null;
            return RedirectToAction("Index", "Home");
        }

    }
}

magasin.web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

magasin.web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

magasin.web/Views/Home/Index.cshtml
@model magasin.DAL.Profil

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron text-center">
    <h1>KeramikBoutik</h1>
    <p>
        Bonjour @Model.Prenom @Model.Nom
        <br />
        Bienvenue sur notre magasin de vente de céramiques online!
    </p>
</div>
@{
    Html.RenderPartial("~/Views/Shared/_Test.cshtml");
}

magasin.web/Views/Home/Register.cshtml
@model magasin.DAL.Profil

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    

        <div class="form-group">
            @Html.LabelFor(model => model.User.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

magasin.web/Views/Object/AfficherObjet.cshtml
@model IEnumerable<magasin.DAL.Object>



@{
    ViewBag.Title = "AfficherObjet";
}

<h2>AfficherObjet</h2>

<p>
    @Html.ActionLink("Create New", "CreerObjetPHOTO")
</p>
<p>
    @Html.ActionLink("Voir panier", "afficherPannier")
</p>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdObjet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdObjet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prix)
                </td>
                <td>


                    @*@Html.DisplayFor(modelItem => item.Photo)*@

                    <img src="~/@item.Photo" alt="pas photo" height="100" width="100"/>
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditObjet", new { id = item.IdObjet }, null) |
                    @Html.ActionLink("Details", "AfficherUnObjet", new { id = item.IdObjet }, null) |
                    @Html.ActionLink("Delete", "DeleteObjet", new { id = item.IdObjet })
                    <button data-id="@item.IdObjet" class='ButtonAjoute'>Buy me</button>

                </td>
            </tr>
        }

    </table>


    <script>
        var buttonsPannier = document.getElementsByClassName('ButtonAjoute');
        /*var id=buttonPannier['id'];*/
        for (var i = 0; i < buttonsPannier.length; i++) {
            var buttonPannier = buttonsPannier[i];
            buttonPannier.addEventListener("click", function (event) {

                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4) {
                        if (xhr.status == 200) {
                            console.log(xhr.responseText);
                            var reponse = JSON.parse(xhr.responseText);
                            console.log(reponse);
                            console.log(typeof (reponse));
                        }
                        else {
                            console.log(xhr.reponseText);
                        }
                    }
                };
                console.log(event.target.getAttribute('data-id'));
                xhr.open('POST', "/Object/traitementAjax", true);
                xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                xhr.send("valeurId=" + event.target.getAttribute('data-id'));
            });
        }

    </script>

magasin.web/Views/Object/AfficherUnObjet.cshtml
@model magasin.DAL.Object

@{
    ViewBag.Title = "AfficherUnObjet";
}

<h2>AfficherUnObjet</h2>

<div>
    <h4>Object</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdObjet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdObjet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Photo)*@
            <img src="~/@Model.Photo" alt="pas photo" height="100" width="100" />

        </dd>
       
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditObjet")  |
    @Html.ActionLink("Back to List", "AfficherObjet")
</p>

magasin.web/Views/Object/CreerObjet.cshtml
@model magasin.web.Models.ObjectCategorie

@using magasin.web.Infrastructure 

@{
    ViewBag.Title = "CreerObjet";
}

<h2>CreerObjet</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Object</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj.Photo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Categorie.NomCategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditSelectNomCategorie(Model.Cats, Model.Obj.IdObjet)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

magasin.web/Views/Object/CreerObjetPHOTO.cshtml
@model magasin.web.Models.ObjectCategorie

@using magasin.web.Infrastructure

@{
    ViewBag.Title = "CreerObjetPHOTO";
}


<h2>CreerObjet</h2>


@using (Html.BeginForm("CreerObjetPHOTO", "Object", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Object</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="col-md-10">
                    <input type="file" id="file" name="file" />
           @Html.ValidationMessageFor(model => model.Obj.Photo, "", new { @class = "text-danger" })        
                </div>

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Obj.Categorie.NomCategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditSelectNomCategorie(Model.Cats, Model.Obj.IdObjet)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AfficherObjet")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

magasin.web/Views/Object/EditObjet.cshtml
@model magasin.DAL.Object

@{
    ViewBag.Title = "EditObjet";
}

<h2>EditObjet</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Object</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdObjet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdObjet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdObjet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="col-md-10">
                    <input type="file" id="file" name="file" />
                    @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AfficherObjet")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

magasin.web/Views/Object/afficherPannier.cshtml
@model IEnumerable<magasin.DAL.Object>

<p>
    @Html.ActionLink("retour shopping", "AfficherObjet")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdObjet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdObjet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Photo)*@
            <img src="~/@item.Photo" alt="pas photo" height="100" width="100" />
        </td>
        <td>
            
            @Html.ActionLink("Details", "AfficherUnObjet", new { id = item.IdObjet }, null) |
            @Html.ActionLink("Delete", "DeleteObjet", new { id = item.IdObjet })
        </td>
    </tr>
}

</table>

magasin.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon Magasin</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("magasin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (@*Session["userConnected"] != default(magasin.DAL.User)*@
magasin.web.Infrastructure.SessionUtils.UserConnected.IdProfil != 0)
                {
                    <li>@Html.ActionLink("Se déconnecter", "Deconnexion", "User")</li>
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Ajouter un objet", "CreerObjetPHOTO", "Object")</li>
                    <li>@Html.ActionLink("Afficher liste objets", "AfficherObjet", "Object")</li>

}
else
{
                <li>@Html.ActionLink("Connection", "Connection", "User")</li>
                <li>@Html.ActionLink("Créer un profil", "Register", "Home")</li>
                <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
}

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

magasin.web/Views/Shared/_Test.cshtml
<h1>Great !!!!!!</h1>

magasin.web/Views/User/Connection.cshtml
@model magasin.DAL.User

@{
    ViewBag.Title = "Connection";
}

<h2>Connection</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}